### ISSUE TITLE
Active Check box Alignment

### ISSUE THREAD

**Issue by ghost** [collecteddoc/Legal#10]
**Path:**  Setup > All Module
**Issue :** Active Check box alignment is not correct while in edit mode.
![Contempt Petition Setup](https://user-images.githubusercontent.com/54391338/63645478-f4b69c80-c720-11e9-9fac-1a09351e9719.png)

**Comment by anil-jaglan** [comment]
Checkbox alignment in record is right in the middle. The only issue here is the filter check box which has a hidden 'reset' text right of it which will be shown upon checking on or off the button.

**Comment by anil-jaglan** [comment]
As discussed with Jilani earlier, it 's fine the have like this.
