### ISSUE TITLE
Date Selection

### ISSUE THREAD

**Issue by ghost** [collecteddoc/Legal#11]
**Path:** High Court Case> Create> **Date of Judgement of Writ Petition**
**Issue:** While clicked on the **Date of Judgement of Writ Petition** field ,Selection from **Calendar** is not available.
![HighcourtCase_date](https://user-images.githubusercontent.com/54391338/63645672-7d373c00-c725-11e9-995c-1886d5718ed3.png)

**Comment by ghost** [comment]
**Not Solved Yet!!!**

**Comment by anil-jaglan** [comment]
there was not any requirement of Calendar in this field. Please ask Jilani if we need to add calendar here.

**Comment by ghost** [comment]
Fixed
