### ISSUE TITLE
Attachment button

### ISSUE THREAD

**Issue by ghost** [collecteddoc/Legal#12]
**Path:**  **High Court Case > Create** 
**Issue:** Clicking on the text box opens browse mode
![attachment](https://user-images.githubusercontent.com/54391338/63645727-765cf900-c726-11e9-855a-873751556070.png)

**Comment by anil-jaglan** [comment]
input box along with 'browse' text is a complete file opening component. Since this is browser default behavior, So we can't restrict it to button only.
