### ISSUE TITLE
NO Mandatory Sign

### ISSUE THREAD

**Issue by ghost** [collecteddoc/Legal#14]
**Path:** Setup>All Module
**Issue:** There is no Mandatory Sign  given for the fields.
![mandatiry sign](https://user-images.githubusercontent.com/54391338/63645869-de144380-c728-11e9-8d7c-a0bb7a720dac.png)

**Comment by anil-jaglan** [comment]
Module can't be created anymore in the system.

**Comment by ghost** [comment]
@jaglans The name module is mandatory, over there no sign is given. but you can not save a record keeping that field empty. You must give a mandatory sign beside each field.

**Comment by ghost** [comment]
@jaglans this issue is not closed yet...
