### ISSUE TITLE
Bangla Name

### ISSUE THREAD

**Issue by ghost** [collecteddoc/Legal#18]
**Path:**  Setup >Any module > Bangla Name
**Issue:**  Accepts input in English.
![bangla name1](https://user-images.githubusercontent.com/54391338/63646185-72ce6f80-c730-11e9-8ec6-1a5770077881.png)

**Comment by anil-jaglan** [comment]
We can't restrict the language input in any of the field. it's only up to the user what language he selects to enter data.
