### ISSUE TITLE
Design Breaks

### ISSUE THREAD

**Issue by ghost** [collecteddoc/Legal#21]
**Path:** Administrative Case >Search 
**Issue:** Field Name and Button position is not correct,alignment is not correct. It breaks the design.
![Administrative case_design issue](https://user-images.githubusercontent.com/54391338/63646369-6dbeef80-c733-11e9-9908-394e224bbaf6.png)

**Comment by anil-jaglan** [comment]
Since Bangla characters are a bit wider than English characters. So a little design issue will always be there.
