### ISSUE TITLE
Do not highlight the empty field

### ISSUE THREAD

**Issue by ghost** [collecteddoc/Legal#22]
**Issue:** While Inserting datas to create a record it gives error but does not highlight the empty field or wrong inputted field.
![Screenshot 2019-08-25 12 33 04](https://user-images.githubusercontent.com/54391338/63646719-01df8580-c739-11e9-9c1c-ce8fff42e163.png)

**Comment by anil-jaglan** [comment]
Due to having limitation of grid library, validation can't be added for inline records. Hence, User herself/himself must have knowledge of mandatory fields.
