### ISSUE TITLE
Password Policy

### ISSUE THREAD

**Issue by ghost** [collecteddoc/Legal#25]
**Issue:**  Password policy is not being maintained as per given.
![password](https://user-images.githubusercontent.com/54391338/63648087-5a6c4e00-c74c-11e9-8cdd-7f1b49aababb.png)

**Comment by anil-jaglan** [comment]
@samiranahar18 , can you please share some details what password policy is getting passed by when changing new password.

**Comment by ghost** [comment]
@jaglans 
Our present password is **"admin"** , which do not have a number, combination of caps and small letter, no special character ,not even the length is correct.So as far as i am concerned the password policy is not maintained while giving it. The validation is not working i guess.

**Comment by anil-jaglan** [comment]
@samiranahar18 , 'admin' is default password which is system generated.

This password policy applies only when user is changing his/her password.

Even, Admin can choose any password while creating a new user.

**Comment by ghost** [comment]
ok
