### ISSUE TITLE
Logs out from the Legal Case Management System

### ISSUE THREAD

**Issue by ghost** [collecteddoc/Legal#26]
**Issue:**  When user clicks on the profile he gets out from the Legal Case Management System.Do not get back to the menu bars when clicked on the **Dashboard**.

**Comment by anil-jaglan** [comment]
Profile button has been removed permanently and was replaced with Change password.

**Comment by ghost** [comment]
From the **Change Password** Page there is no **Back** button, And When Clicked on the **Dashboard** Module then It takes out from the **Legal Management System.**

**Comment by anil-jaglan** [comment]
Since, Change password feature is in ACL module. Hence user module will be changed automatically when user clicks on change password option, no matter which module user is working in. 
I don't see any point to give a back button option here.
