### ISSUE TITLE
Wrong Login message

### ISSUE THREAD

**Issue by ghost** [collecteddoc/Legal#29]
**Issue:**  The login message should come with a pop up and Notify that"User Name / Password is Invalid. "
![sign in](https://user-images.githubusercontent.com/54391338/63648350-6eb24a00-c750-11e9-852c-8388c1c20bcf.png)

**Comment by anil-jaglan** [comment]
Forgot password is not yet implemented because we don't have any email system working. It's only in page design.... As far as re captcha is concerned, It will be integrated in next version.

**Comment by ghost** [comment]
It is not solved yet. S it should be kept open as bug until its fixed.

**Comment by anil-jaglan** [comment]
Fixed.
