### ISSUE TITLE
3. High Court Case-> Search-> View->  * Petitioner value is showing id. Should be Name. * After attaching a file it should be shown the attachment name at box. 

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/Legal#3]
![image](https://user-images.githubusercontent.com/52271735/60500666-8c2cdf80-9cdc-11e9-882e-c857194f77ad.png)

![image](https://user-images.githubusercontent.com/52271735/60500930-f8a7de80-9cdc-11e9-9a83-9a30a6380509.png)

![image](https://user-images.githubusercontent.com/52271735/60500944-fe052900-9cdc-11e9-9403-1635e9105554.png)

**Comment by anil-jaglan** [comment]
Fixed. Need to deploy a new version.
