### ISSUE TITLE
ACL 

### ISSUE THREAD

**Issue by collecteddoc** [collecteddoc/Legal#30]
- [ ] 1.	Users should have access to the Menus according to their access.
- [x] 2.	Data Isolation
- [x] 3.	In Users > Create; Change the position of Role and Module.
- [x] 4.	 Roles will be suggested according to the selection of Module.

- [x] 5. In Menu > List, Hide Delete Icon.

- [x] 6.	Hide the Create Submenu from Menu Module.
- [x] 7.	In Menu > List; Link columns texts should be disabled.
- [x] 8.	In Menu > List; Hidden Column is not required.
- [x] 9.	In Menu > List; Menu Title, Sort Order, Active icon should be only editable others should be fixed, non-editable.
- [x] 10.	In Menu > Manage, Module, menu permission field name, or check box is not needed. Change it into Arrow Icon.
- [x] 11.	A Captcha should be available in the login page. It should be similar like the PMIS. <Mathematical Equation >
- [x] 12.	If User selects the Remember ME option then the session will be remembered for 1 day.
- [x] 13.	In case of Forget Password, the flow will be like; User Name > Email > Click on the Link > Reset Password.
- [x] 14.	User Mapping, One user can be assigned to multiple modules and roles can be selected according to them.
- [x] 15.	In case of Session Out, a session out message should be provided for the users.

**Comment by ghost** [comment]
-  In **Menu > Manage**, Module, menu permission field name, or check box is not needed. Change it into Arrow Icon. **Solved in different way. Did not  add arrow but  menu permission and Check box is removed from the list**

-   If User selects the Remember ME option then the session will be remembered for 1 day. **It will be reported tomorrow** 

- In case of **Forgot Password,** Does not recognize the **user name** .
![user name](https://user-images.githubusercontent.com/54391338/65826320-7790c100-e2a4-11e9-8a46-52a8ee985052.png)

- {In case of Session Out, a session out message should be provided for the users.} - **Does not give any session out message** -**Fail**
- **User Role > List > Edit** ; even after deactivating a user role, user can have access to all the modules. Which should not be.

**Comment by ghost** [comment]
In **Users >List** ; Role for O&M is not showing the correct role. 
![wrong User showing](https://user-images.githubusercontent.com/54391338/65828287-13c5c280-e2bb-11e9-8174-adaa26d64d26.png)

**Comment by anil-jaglan** [comment]
O&amp;M_USER is actually O&M_USER .... Since it contains special character, so it is encoded by the library used for drop down. It can't fixed. 

I have a recommendation of not using the special characters.

**Comment by anil-jaglan** [comment]
Point no 13 -> In case of Forget Password, the flow will be like; User Name > Email > Click on the Link > Reset Password.

We don't need to show email here. By asking a user to prove the email is not safe for security purpose and also it includes one more check. It will be good to ask username from user to identification.

**Comment by ghost** [comment]
**Path:**    **Menu bar** 
** Issue: ** Arrows should be in outward corner.
![menu bar arrow](https://user-images.githubusercontent.com/54391338/66474289-cf080b80-eab2-11e9-8c41-5b886517dc3b.png)

**Comment by ghost** [comment]
**Issue no-7 :** In **Menu > List** ; Link columns texts should be disabled. - **FIXED**
**Reference : **

![legal](https://user-images.githubusercontent.com/54391338/66474862-f7dcd080-eab3-11e9-80d6-4e4a0f2cf2ec.gif)

**Comment by ghost** [comment]
1. Users should have access to the Menus according to their access.- **Fixed**
2. Data isolation fixed. 
 3. In Users > Create; Change the position of Role and Module.  **Fixed**
4.Roles will be suggested according to the selection of Module.   **Fixed**
5. In Menu > List, Hide Delete Icon.  **Fixed**
6. Hide the Create Submenu from Menu Module.  **Fixed**
8. In Menu > List; Hidden Column is not required.  **Fixed**
9. In Menu > List; Menu Title, Sort Order, Active icon should be only editable others should be fixed, non-editable. < Only ID and Link option is fixed others are editable.> - **Not Fixed**
 10. In Menu > Manage, Module, menu permission field name, or check box is not needed. Change it into Arrow Icon. **Fixed**
11. A Captcha should be available in the login page. It should be similar like the PMIS.
12. 14. User Mapping, One user can be assigned to multiple modules and roles can be selected according to them.- **Fixed**
 15. In case of **Session Out**, a session out message should be provided for the users. **<Could not test Yet>**

**Comment by ghost** [comment]
13. In case of **Forget Password**, the flow will be like; User Name > Email > Click on the Link > Reset Password. **<not fixed Yet>** **Does not recognize User ID**
![forgt pw](https://user-images.githubusercontent.com/54391338/66476389-4a6bbc00-eab7-11e9-86cd-e9e457966ed7.png)
